# -----------------------------------------------------------------------------
# File: mkdocs.yml
# Description: MkDocs config for building Markdown API docs with mkdocstrings
# -----------------------------------------------------------------------------

site_name: Geo Documentation
site_description: API reference for the GeoEntities system
site_author: Jack Matanky

docs_dir: docs
site_dir: site

theme:
    name: material
    features:
        - content.code.copy
        - navigation.indexes
        - navigation.tabs
        - search.suggest

plugins:
    - search
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  setup_commands:
                      - import sys
                      - sys.path.append("src")
                  options:
                      show_root_heading: true
                      show_source: false
                      merge_init_into_class: true
                      separate_signature: true
                      docstring_style: google
                      show_signature_annotations: true

markdown_extensions:
    - toc:
          permalink: true
    - admonition
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.emoji

nav:
    - Home: index.md
    - API Reference:
          - Geo Entities: reference/geo_entities.md
          - Shared: reference/shared.md
          - Geo Utils: reference/geo_utils.md
