# -----------------------------------------------------------------------------
# File: ${PROJECT_PATH}/.pre-commit-config.yaml
# Docs: https://pre-commit.com/
# Description: Pre-commit hooks for code quality, notebook sync, and hygiene
# -----------------------------------------------------------------------------

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.3.2
      hooks:
          - id: ruff
            args: [--fix] # Remove this if you prefer to only lint without auto-fixing

    - repo: https://github.com/mwouts/jupytext
      rev: master
      hooks:
          - id: jupytext-synchronize
